name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore packages
      run: msbuild RAWGPlaynitePlugin.sln /t:restore
    - name: Build
      run: msbuild RAWGPlaynitePlugin.sln /t:build
