/* 
 * RAWG Video Games Database API
 *
 *  The largest open video games database.  ### Why build on RAWG - More than 350,000 games for 50 platforms including mobiles. - Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates, Metacritic ratings. - Where to buy: links to digital distribution services - Similar games based on visual similarity. - Player activity data: Steam average playtime and RAWG player counts and ratings. - Actively developing and constantly getting better by user contribution and our algorithms.  ### Terms of Use - Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active hyperlink from every page where the data of RAWG is used. - Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for commercial terms. - No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt, and we will talk it through. - Every API request should have a User-Agent header with your app name. If you don???t provide it, we may ban your requests.  __[Read more](https://rawg.io/apidocs)__. 
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Rawg.Model
{
    /// <summary>
    /// PlatformSingle
    /// </summary>
    [DataContract]
    public partial class PlatformSingle :  IEquatable<PlatformSingle>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformSingle" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PlatformSingle() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PlatformSingle" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="description">description.</param>
        /// <param name="yearStart">yearStart.</param>
        /// <param name="yearEnd">yearEnd.</param>
        public PlatformSingle(string name = default(string), string description = default(string), int? yearStart = default(int?), int? yearEnd = default(int?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for PlatformSingle and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            this.Description = description;
            this.YearStart = yearStart;
            this.YearEnd = yearEnd;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [DataMember(Name="slug", EmitDefaultValue=false)]
        public string Slug { get; private set; }

        /// <summary>
        /// Gets or Sets GamesCount
        /// </summary>
        [DataMember(Name="games_count", EmitDefaultValue=false)]
        public int? GamesCount { get; private set; }

        /// <summary>
        /// Gets or Sets ImageBackground
        /// </summary>
        [DataMember(Name="image_background", EmitDefaultValue=false)]
        public string ImageBackground { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name="image", EmitDefaultValue=false)]
        public string Image { get; private set; }

        /// <summary>
        /// Gets or Sets YearStart
        /// </summary>
        [DataMember(Name="year_start", EmitDefaultValue=false)]
        public int? YearStart { get; set; }

        /// <summary>
        /// Gets or Sets YearEnd
        /// </summary>
        [DataMember(Name="year_end", EmitDefaultValue=false)]
        public int? YearEnd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlatformSingle {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  GamesCount: ").Append(GamesCount).Append("\n");
            sb.Append("  ImageBackground: ").Append(ImageBackground).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  YearStart: ").Append(YearStart).Append("\n");
            sb.Append("  YearEnd: ").Append(YearEnd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlatformSingle);
        }

        /// <summary>
        /// Returns true if PlatformSingle instances are equal
        /// </summary>
        /// <param name="input">Instance of PlatformSingle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlatformSingle input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Slug == input.Slug ||
                    (this.Slug != null &&
                    this.Slug.Equals(input.Slug))
                ) && 
                (
                    this.GamesCount == input.GamesCount ||
                    (this.GamesCount != null &&
                    this.GamesCount.Equals(input.GamesCount))
                ) && 
                (
                    this.ImageBackground == input.ImageBackground ||
                    (this.ImageBackground != null &&
                    this.ImageBackground.Equals(input.ImageBackground))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Image == input.Image ||
                    (this.Image != null &&
                    this.Image.Equals(input.Image))
                ) && 
                (
                    this.YearStart == input.YearStart ||
                    (this.YearStart != null &&
                    this.YearStart.Equals(input.YearStart))
                ) && 
                (
                    this.YearEnd == input.YearEnd ||
                    (this.YearEnd != null &&
                    this.YearEnd.Equals(input.YearEnd))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Slug != null)
                    hashCode = hashCode * 59 + this.Slug.GetHashCode();
                if (this.GamesCount != null)
                    hashCode = hashCode * 59 + this.GamesCount.GetHashCode();
                if (this.ImageBackground != null)
                    hashCode = hashCode * 59 + this.ImageBackground.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Image != null)
                    hashCode = hashCode * 59 + this.Image.GetHashCode();
                if (this.YearStart != null)
                    hashCode = hashCode * 59 + this.YearStart.GetHashCode();
                if (this.YearEnd != null)
                    hashCode = hashCode * 59 + this.YearEnd.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if(this.Name != null && this.Name.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if(this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Slug (string) minLength
            if(this.Slug != null && this.Slug.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Slug, length must be greater than 1.", new [] { "Slug" });
            }

            // Slug (string) pattern
            Regex regexSlug = new Regex(@"^[-a-zA-Z0-9_]+$", RegexOptions.CultureInvariant);
            if (false == regexSlug.Match(this.Slug).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Slug, must match a pattern of " + regexSlug, new [] { "Slug" });
            }

            // YearStart (int?) maximum
            if(this.YearStart > (int?)32767)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for YearStart, must be a value less than or equal to 32767.", new [] { "YearStart" });
            }

            // YearStart (int?) minimum
            if(this.YearStart < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for YearStart, must be a value greater than or equal to 0.", new [] { "YearStart" });
            }

            // YearEnd (int?) maximum
            if(this.YearEnd > (int?)32767)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for YearEnd, must be a value less than or equal to 32767.", new [] { "YearEnd" });
            }

            // YearEnd (int?) minimum
            if(this.YearEnd < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for YearEnd, must be a value greater than or equal to 0.", new [] { "YearEnd" });
            }

            yield break;
        }
    }

}
